"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def partial_duplication_graph(N, n, p, q, seed: Incomplete | None = ...):
    ...

def duplication_divergence_graph(n, p, seed: Incomplete | None = ...):
    ...

