"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def ego_graph(G, n, radius: float = ..., center: bool = ..., undirected: bool = ..., distance: Incomplete | None = ...):
    ...

