"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def hnm_harary_graph(n, m, create_using: Incomplete | None = ...):
    ...

def hkn_harary_graph(k, n, create_using: Incomplete | None = ...):
    ...

