"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import TypeVar, overload
from networkx import MultiGraph
from networkx.classes.graph import Graph
from networkx.utils.misc import _RandomState

_G = TypeVar("_G", bound=Graph[int])
@overload
def random_clustered_graph(joint_degree_sequence: Iterable[tuple[int, int]], create_using: None = ..., seed: _RandomState = ...) -> MultiGraph[int]:
    ...

@overload
def random_clustered_graph(joint_degree_sequence: Iterable[tuple[int, int]], create_using: type[_G], seed: _RandomState = ...) -> _G:
    ...

