"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def prefix_tree(paths):
    ...

def prefix_tree_recursive(paths):
    ...

def random_tree(n, seed: Incomplete | None = ..., create_using: Incomplete | None = ...):
    ...

