"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

def bfs_beam_edges(G, source, value, width: Incomplete | None = ...) -> Generator[Incomplete, Incomplete, Incomplete]:
    ...

