"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def modularity_matrix(G, nodelist: Incomplete | None = ..., weight: Incomplete | None = ...):
    ...

def directed_modularity_matrix(G, nodelist: Incomplete | None = ..., weight: Incomplete | None = ...):
    ...

