"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator
from typing import overload
from networkx.classes.graph import Graph, _Node

def has_path(G, source, target):
    ...

@overload
def shortest_path(G: Graph[_Node], source: _Node, target: _Node, weight: Incomplete | None = ..., method: str = ...) -> list[_Node]:
    ...

@overload
def shortest_path(G: Graph[_Node], target: _Node, method: str = ...) -> dict[_Node, list[_Node]]:
    ...

@overload
def shortest_path(G: Graph[_Node], source: _Node, method: str = ...) -> dict[_Node, list[_Node]]:
    ...

def shortest_path_length(G, source: Incomplete | None = ..., target: Incomplete | None = ..., weight: Incomplete | None = ..., method: str = ...):
    ...

def average_shortest_path_length(G, weight: Incomplete | None = ..., method: str | None = ...):
    ...

def all_shortest_paths(G: Graph[_Node], source: _Node, target: _Node, weight: Incomplete | None = ..., method: str = ...) -> Generator[list[_Node], None, None]:
    ...

