"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def average_degree_connectivity(G, source: str = ..., target: str = ..., nodes: Incomplete | None = ..., weight: Incomplete | None = ...):
    ...

