"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def hits(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ...):
    ...

