"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def pagerank(G, alpha: float = ..., personalization: Incomplete | None = ..., max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., weight: str = ..., dangling: Incomplete | None = ...):
    ...

def google_matrix(G, alpha: float = ..., personalization: Incomplete | None = ..., nodelist: Incomplete | None = ..., weight: str = ..., dangling: Incomplete | None = ...):
    ...

