"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

def girvan_newman(G, most_valuable_edge: Incomplete | None = ...) -> Generator[Incomplete, None, Incomplete]:
    ...

