"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

def k_clique_communities(G, k, cliques: Incomplete | None = ...) -> Generator[Incomplete, None, None]:
    ...

