"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def kernighan_lin_bisection(G, partition: Incomplete | None = ..., max_iter: int = ..., weight: str = ..., seed: Incomplete | None = ...):
    ...

