"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

def asyn_lpa_communities(G, weight: Incomplete | None = ..., seed: Incomplete | None = ...) -> Generator[Incomplete, Incomplete, None]:
    ...

def label_propagation_communities(G):
    ...

