"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def lukes_partitioning(G, max_size, node_weight: Incomplete | None = ..., edge_weight: Incomplete | None = ...):
    ...

