"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def greedy_modularity_communities(G, weight: Incomplete | None = ..., resolution: float = ..., cutoff: int = ..., best_n: Incomplete | None = ...):
    ...

def naive_greedy_modularity_communities(G, resolution: float = ..., weight: Incomplete | None = ...):
    ...

