"""
This type stub file was generated by pyright.
"""

from networkx.exception import NetworkXError

__all__ = ["modularity", "partition_quality"]
class NotAPartition(NetworkXError):
    def __init__(self, G, collection) -> None:
        ...
    


def modularity(G, communities, weight: str = ..., resolution: float = ...):
    ...

def partition_quality(G, partition):
    ...

