"""
This type stub file was generated by pyright.
"""

__all__ = ["_dispatch", "_mark_tests"]
class PluginInfo:
    def __init__(self) -> None:
        ...
    
    def __bool__(self) -> bool:
        ...
    
    @property
    def items(self):
        ...
    
    def __contains__(self, name) -> bool:
        ...
    
    def __getitem__(self, name):
        ...
    


