"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def min_weighted_dominating_set(G, weight: Incomplete | None = ...):
    ...

def min_edge_dominating_set(G):
    ...

