"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def metric_closure(G, weight: str = ...):
    ...

def steiner_tree(G, terminal_nodes, weight: str = ..., method: Incomplete | None = ...):
    ...

