"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

__all__ = ["average_node_connectivity", "local_node_connectivity", "node_connectivity", "local_edge_connectivity", "edge_connectivity", "all_pairs_node_connectivity"]
default_flow_func = ...
def local_node_connectivity(G, s, t, flow_func: Incomplete | None = ..., auxiliary: Incomplete | None = ..., residual: Incomplete | None = ..., cutoff: Incomplete | None = ...):
    ...

def node_connectivity(G, s: Incomplete | None = ..., t: Incomplete | None = ..., flow_func: Incomplete | None = ...):
    ...

def average_node_connectivity(G, flow_func: Incomplete | None = ...):
    ...

def all_pairs_node_connectivity(G, nbunch: Incomplete | None = ..., flow_func: Incomplete | None = ...):
    ...

def local_edge_connectivity(G, s, t, flow_func: Incomplete | None = ..., auxiliary: Incomplete | None = ..., residual: Incomplete | None = ..., cutoff: Incomplete | None = ...):
    ...

def edge_connectivity(G, s: Incomplete | None = ..., t: Incomplete | None = ..., flow_func: Incomplete | None = ..., cutoff: Incomplete | None = ...):
    ...

