"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

__all__ = ["minimum_st_node_cut", "minimum_node_cut", "minimum_st_edge_cut", "minimum_edge_cut"]
default_flow_func = ...
def minimum_st_edge_cut(G, s, t, flow_func: Incomplete | None = ..., auxiliary: Incomplete | None = ..., residual: Incomplete | None = ...):
    ...

def minimum_st_node_cut(G, s, t, flow_func: Incomplete | None = ..., auxiliary: Incomplete | None = ..., residual: Incomplete | None = ...):
    ...

def minimum_node_cut(G, s: Incomplete | None = ..., t: Incomplete | None = ..., flow_func: Incomplete | None = ...):
    ...

def minimum_edge_cut(G, s: Incomplete | None = ..., t: Incomplete | None = ..., flow_func: Incomplete | None = ...):
    ...

