"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ["edge_disjoint_paths", "node_disjoint_paths"]
default_flow_func = ...
def edge_disjoint_paths(G, s, t, flow_func: Incomplete | None = ..., cutoff: Incomplete | None = ..., auxiliary: Incomplete | None = ..., residual: Incomplete | None = ...) -> Generator[Incomplete, None, None]:
    ...

def node_disjoint_paths(G, s, t, flow_func: Incomplete | None = ..., cutoff: Incomplete | None = ..., auxiliary: Incomplete | None = ..., residual: Incomplete | None = ...) -> Generator[Incomplete, None, None]:
    ...

