"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

__all__ = ["k_components"]
default_flow_func = ...
def k_components(G, flow_func: Incomplete | None = ...):
    ...

