"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ["all_node_cuts"]
default_flow_func = ...
def all_node_cuts(G, k: Incomplete | None = ..., flow_func: Incomplete | None = ...) -> Generator[Incomplete, None, None]:
    ...

