"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def current_flow_closeness_centrality(G, weight: Incomplete | None = ..., dtype=..., solver: str = ...):
    ...

information_centrality = ...
