"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def dispersion(G, u: Incomplete | None = ..., v: Incomplete | None = ..., normalized: bool = ..., alpha: float = ..., b: float = ..., c: float = ...):
    ...

