"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def harmonic_centrality(G, nbunch: Incomplete | None = ..., distance: Incomplete | None = ..., sources: Incomplete | None = ...):
    ...

