"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def laplacian_centrality(G, normalized: bool = ..., nodelist: Incomplete | None = ..., weight: str = ..., walk_type: Incomplete | None = ..., alpha: float = ...):
    ...

