"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def percolation_centrality(G, attribute: str = ..., states: Incomplete | None = ..., weight: Incomplete | None = ...):
    ...

