"""
This type stub file was generated by pyright.
"""

def subgraph_centrality_exp(G):
    ...

def subgraph_centrality(G):
    ...

def communicability_betweenness_centrality(G):
    ...

def estrada_index(G):
    ...

