"""
This type stub file was generated by pyright.
"""

def trophic_levels(G, weight: str = ...):
    ...

def trophic_differences(G, weight: str = ...):
    ...

def trophic_incoherence_parameter(G, weight: str = ..., cannibalism: bool = ...):
    ...

