"""
This type stub file was generated by pyright.
"""

def union_all(graphs, rename=...):
    ...

def disjoint_union_all(graphs):
    ...

def compose_all(graphs):
    ...

def intersection_all(graphs):
    ...

