"""
This type stub file was generated by pyright.
"""

def degree_centrality(G, nodes):
    ...

def betweenness_centrality(G, nodes):
    ...

def closeness_centrality(G, nodes, normalized: bool = ...):
    ...

