"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def latapy_clustering(G, nodes: Incomplete | None = ..., mode: str = ...):
    ...

clustering = ...
def average_clustering(G, nodes: Incomplete | None = ..., mode: str = ...):
    ...

def robins_alexander_clustering(G):
    ...

