"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def dinitz(G, s, t, capacity: str = ..., residual: Incomplete | None = ..., value_only: bool = ..., cutoff: Incomplete | None = ...):
    ...

