"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

__all__ = ["gomory_hu_tree"]
default_flow_func = ...
def gomory_hu_tree(G, capacity: str = ..., flow_func: Incomplete | None = ...):
    ...

