"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

__all__ = ["maximum_flow", "maximum_flow_value", "minimum_cut", "minimum_cut_value"]
default_flow_func = ...
def maximum_flow(flowG, _s, _t, capacity: str = ..., flow_func: Incomplete | None = ..., **kwargs):
    ...

def maximum_flow_value(flowG, _s, _t, capacity: str = ..., flow_func: Incomplete | None = ..., **kwargs):
    ...

def minimum_cut(flowG, _s, _t, capacity: str = ..., flow_func: Incomplete | None = ..., **kwargs):
    ...

def minimum_cut_value(flowG, _s, _t, capacity: str = ..., flow_func: Incomplete | None = ..., **kwargs):
    ...

