"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def preflow_push(G, s, t, capacity: str = ..., residual: Incomplete | None = ..., global_relabel_freq: float = ..., value_only: bool = ...):
    ...

