"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Callable, Generator
from typing import Literal, overload
from networkx.classes.graph import Graph, _Node

def bridges(G: Graph[_Node], root: _Node | None = ...) -> Generator[_Node, None, None]:
    ...

def has_bridges(G: Graph[_Node], root: Incomplete | None = ...) -> bool:
    ...

@overload
def local_bridges(G: Graph[_Node], with_span: Literal[False], weight: str | Callable[[_Node], float] | None = ...) -> Generator[tuple[_Node, _Node], None, None]:
    ...

@overload
def local_bridges(G: Graph[_Node], with_span: Literal[True] = ..., weight: str | Callable[[_Node], float] | None = ...) -> Generator[tuple[_Node, _Node, int], None, None]:
    ...

