"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator
from networkx.classes.graph import Graph, _Node

def chain_decomposition(G: Graph[_Node], root: _Node | None = ...) -> Generator[list[tuple[_Node, _Node]], None, None]:
    ...

