"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Generator

def cycle_basis(G, root: Incomplete | None = ...):
    ...

def simple_cycles(G, length_bound: Incomplete | None = ...) -> Generator[Incomplete, Incomplete, None]:
    ...

class _NeighborhoodCache(dict[Incomplete, Incomplete]):
    G: Incomplete
    def __init__(self, G) -> None:
        ...
    
    def __missing__(self, v):
        ...
    


def chordless_cycles(G, length_bound: Incomplete | None = ...) -> Generator[Incomplete, Incomplete, None]:
    ...

def recursive_simple_cycles(G):
    ...

def find_cycle(G, source: Incomplete | None = ..., orientation: Incomplete | None = ...):
    ...

def minimum_cycle_basis(G, weight: Incomplete | None = ...):
    ...

