"""
This type stub file was generated by pyright.
"""

def is_distance_regular(G):
    ...

def global_parameters(b, c):
    ...

def intersection_array(G):
    ...

def is_strongly_regular(G):
    ...

