"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def eccentricity(G, v: Incomplete | None = ..., sp: Incomplete | None = ..., weight: Incomplete | None = ...):
    ...

def diameter(G, e: Incomplete | None = ..., usebounds: bool = ..., weight: Incomplete | None = ...):
    ...

def periphery(G, e: Incomplete | None = ..., usebounds: bool = ..., weight: Incomplete | None = ...):
    ...

def radius(G, e: Incomplete | None = ..., usebounds: bool = ..., weight: Incomplete | None = ...):
    ...

def center(G, e: Incomplete | None = ..., usebounds: bool = ..., weight: Incomplete | None = ...):
    ...

def barycenter(G, weight: Incomplete | None = ..., attr: Incomplete | None = ..., sp: Incomplete | None = ...):
    ...

def resistance_distance(G, nodeA, nodeB, weight: Incomplete | None = ..., invert_weight: bool = ...):
    ...

