"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def dominating_set(G, start_with: Incomplete | None = ...):
    ...

def is_dominating_set(G, nbunch):
    ...

