"""
This type stub file was generated by pyright.
"""

def harmonic_function(G, max_iter: int = ..., label_name: str = ...):
    ...

def local_and_global_consistency(G, alpha: float = ..., max_iter: int = ..., label_name: str = ...):
    ...

