"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def is_threshold_graph(G):
    ...

def find_threshold_graph(G, create_using: Incomplete | None = ...):
    ...

