"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def closeness_vitality(G, node: Incomplete | None = ..., weight: Incomplete | None = ..., wiener_index: Incomplete | None = ...):
    ...

