"""
This type stub file was generated by pyright.
"""

from networkx.exception import NetworkXException

class NotATree(NetworkXException):
    ...


def to_nested_tuple(T, root, canonical_form: bool = ...):
    ...

def from_nested_tuple(sequence, sensible_relabeling: bool = ...):
    ...

def to_prufer_sequence(T):
    ...

def from_prufer_sequence(sequence):
    ...

