"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete
from collections.abc import Callable, Hashable
from io import TextIOBase
from typing_extensions import TypeAlias
from networkx.classes.graph import Graph, _Node

_AGraph: TypeAlias = ...
def from_agraph(A, create_using: Incomplete | None = ...) -> Graph[Incomplete]:
    ...

def to_agraph(N: Graph[Hashable]) -> _AGraph:
    ...

def write_dot(G: Graph[Hashable], path: str | TextIOBase) -> None:
    ...

def read_dot(path: str | TextIOBase) -> Graph[Incomplete]:
    ...

def graphviz_layout(G: Graph[_Node], prog: str = ..., root: str | None = ..., args: str = ...) -> dict[_Node, tuple[float, float]]:
    ...

pygraphviz_layout = ...
def view_pygraphviz(G: Graph[_Node], edgelabel: str | Callable[[_Node], str] | None = ..., prog: str = ..., args: str = ..., suffix: str = ..., path: str | None = ..., show: bool = ...):
    ...

