"""
This type stub file was generated by pyright.
"""

from _typeshed import Incomplete

def to_latex_raw(G, pos: str = ..., tikz_options: str = ..., default_node_options: str = ..., node_options: str = ..., node_label: str = ..., default_edge_options: str = ..., edge_options: str = ..., edge_label: str = ..., edge_label_options: str = ...):
    ...

def to_latex(Gbunch, pos: str = ..., tikz_options: str = ..., default_node_options: str = ..., node_options: str = ..., node_label: str = ..., default_edge_options: str = ..., edge_options: str = ..., edge_label: str = ..., edge_label_options: str = ..., caption: str = ..., latex_label: str = ..., sub_captions: Incomplete | None = ..., sub_labels: Incomplete | None = ..., n_rows: int = ..., as_document: bool = ..., document_wrapper: str = ..., figure_wrapper: str = ..., subfigure_wrapper: str = ...):
    ...

def write_latex(Gbunch, path, **options) -> None:
    ...

